### ISSUE TITLE
Question: pros and cons of vim-flog?

### ISSUE THREAD

**Issue by tracyone** [rbong/vim-flog#15]
vim-flog VS [gregsexton/gitv](https://github.com/gregsexton/gitv), what's the difference?

**Comment by polyzen** [comment]
Also https://github.com/junegunn/gv.vim

**Comment by rbong** [comment]
Overall:
- gv is a very minimal commit browser. It's good if all you just want to browse the commit tree and look at commits. I won't be comparing it further because none of my other comparisons apply but it's a good plugin
- gitv is a heavy commit browser. It has tons and tons of features, but it's hard to customize or use it in unexpected ways, and it is prone to bugs (only because it didn't have anything like itself to learn from when it was being built!)
- flog is designed to do everything gitv can do using more generalized, powerful features, but the interface may seem unfamiliar to gitv users since it had to be changed so drastically. It's designed to be light and stable despite its power

Command interface:
- gitv modifies arguments and sends them directly to `git-log`, which cannot handle all possible arguments
- flog has a well defined interface to `git-log` with predefined supported arguments and robust completion, and still allows passing arguments through directly

Window management:
- gitv has two predefined window layouts. It supports opening a secondary window to preview commits. The window layout has little flexibility and is prone to bugs
- flog supports any window layout, and allows multiple preview windows, preview windows opened by custom commands, and windows opened anywhere using builtin vim command modifiers. It's made to do all of this while still being more stable than gitv, since it was written from the ground up with all of this in mind

Git commands:
- gitv supports a handful of custom git commands with predefined arguments tied to many keybindings. Unfortunately adding a new keybinding for every git command makes all of the bindings hard to memorize, and this can never account for every git command
- flog supports running any git command using an ex command, providing extensive ref completion based on the position of the cursor, with additional completion options in visual selection mode. It's possible to set your own keybindings to do everything gitv can do using this system and more, so you'll have just all of the keybindings you need

Public interface:
- gitv is not designed to expose any of its internal functions. Internally, it interacts with the currently loaded commits via regex
- flog exposes all of its functions and keeps them well organized and well defined. Besides just allowing anyone to easily extend flog, this has the added benefit of making it very easy to maintain, and it prevents bugs. Flog builds an object with all of the information it can gather about the currently shown commit history, making it easy to get even low level information about the current output. This also makes flog perform much faster than gitv's regex operations and makes it much easier to debug

Sorry if this is messy and long winded... I don't have a lot of time to make a really extensive and compact comparison right now, but I think this covers all of the major points. Please let me know if you have any more questions!

**Comment by polyzen** [comment]
> gv ... does not require fugitive.

Just a note that it's mentioned as a requirement: https://github.com/junegunn/gv.vim#installation

**Comment by rbong** [comment]
Fixed, thank you

**Comment by rbong** [comment]
@polyzen fixed, thank you

**Comment by rbong** [comment]
I knew I was forgetting at least one important thing.

Formatting:
- gitv does not support custom formatting.
- flog supports any custom format, including multiline formats.

**Comment by rbong** [comment]
I've added a more succinct comparison to the newly added [FAQ](https://github.com/rbong/vim-flog#faq)  so I'm closing this. Please reopen or post a new issue if you have any more questions!
