### ISSUE TITLE
Feature Request: use <kbd>q</kbd> for quit / close Flog

### ISSUE THREAD

**Issue by dhruvasagar** [rbong/vim-flog#2]
Fugitive allows closing of fugitive custom buffers like `:Gstatus`, `:Gblame` etc by using <kbd>q</kbd>, I think this should be the default for Flog as well instead of the <kbd>ZZ</kbd>.

**Comment by rbong** [comment]
There's potential in Flog for recording macros compared to `:Gstatus` and `:Gblame`, so I would like to avoid mapping the `q` key by default.

Here's how you can add this mapping:

```vim
augroup myfloggroup
    autocmd FileType floggraph map <buffer> <silent> q <Plug>Flogquit
    autocmd FileType floggraph map <buffer> <silent> ZZ <Plug>Flogquit
augroup END
```

**Comment by dhruvasagar** [comment]
What good are macros on a readonly buffer ? I can't imagine a use case, if it were so, the same argument would be applicable for gblame, gstatus, etc too.

**Comment by rbong** [comment]
Here's one potential workflow with macros - open the log in some way, explore commits using `<C-n>`, determine if some action needs to be performed, perform said action with a macro with the commit on the current line then send `<C-n>` at the end of the macro automatically to go to the next commit.

The way I think of it is that `:Gstatus` and `:Gblame` are singular purpose, whereas Flog is designed to be a launching point into lots of different commands. Note that the commit preview window, which is managed by fugitive, also does not have the `q` bindings.

That's just my thought process for the default mapping, though. The `<Plug>Flogquit` special binding is provided exactly for this purpose. Please refer to the [philosophy of Flog](https://github.com/rbong/vim-flog/blob/master/CONTRIBUTING.md):

>Take advantage of Vim and fugitive's builtin features ... Let users customize how they use Flog so they can use their personal workflows and preferred interface.

This is a case where I would like to let users customize how they use it should they so wish using Vim's remapping capabilities, otherwise I'm just stopping someone from recording macros inside Flog by default.

**Comment by rbong** [comment]
Please note that fugitive now favors gq, and now flog supports this keybinding by default.
