### ISSUE TITLE
escape characters in output 

### ISSUE THREAD

**Issue by hovnatan** [rbong/vim-flog#20]
In my terminal sometimes I have escape characters in the output:

```
1 * ^[[34m2019-11-07 12:45:33 +0400^[[m ^[[33m[52e5b05]^[[m ^[[32m{Hovna
2 * ^[[34m2019-11-07 10:40:22 +0400^[[m ^[[33m[c709740]^[[m ^[[32m{Hovna
3 * ^[[34m2019-11-06 17:11:28 +0400^[[m ^[[33m[d67c1eb]^[[m ^[[32m{Hovna
```

**Comment by rbong** [comment]
Those are color codes that should only show up if you set the `g:flog_use_ansi_esc` variable to 1 and [AnsiEsc.vim](https://github.com/vim-scripts/AnsiEsc.vim) isn't working or if you pass in the `--color` option.

If that doesn't sound right please post the value of the following variables inside the flog window.

* g:flog_use_ansi_esc
* flog#get_state().previous_log_command

The second variable will be long.
You can use `let @+ = flog#get_state().previous_log_command` to copy it to your clipboard if you have clipboard support, otherwise you will have to use `echo flog#get_state().previous_log_command` to get the value.

Please also post the output of `git --version` and check if you have any configuration at `~/.config/git`.

**Comment by hovnatan** [comment]
1. `E121: Undefined variable: g:flog_use_ansi_esc`
2. `git --git-dir=/home/hovnatan/.dotfiles/.git log --graph --no-color --pretty='format:__FSTART__%D__FSEP__%h__FSEP____DSTART__%Cblue%ad%Creset %C(yellow)[%h]%Cre
set %Cgreen{%an}%Creset%Cred%d%Creset %s__DEND____FEND__' --date='iso8601'`
3. `git version 2.7.4`
4. My `.gitconfig` is at [https://github.com/hovnatan/dotfiles/blob/master/.gitconfig](url)

**Comment by hovnatan** [comment]
Ok, installing `git 2.23.0` solved the problem.

**Comment by rbong** [comment]
Awesome, glad that fixed it. Thank you for reporting the issue.
