### ISSUE TITLE
Window flicker when changing a preview window.

### ISSUE THREAD

**Issue by kevinhwang91** [rbong/vim-flog#21]
I am used to gitv and begin to switch to flog because gitv is no maintenance now. 

Unfortunately, the window flicker that annoys me.

![flicker](https://user-images.githubusercontent.com/17562139/68486680-8cd21580-027c-11ea-97a9-3866c30b9887.gif)
I also try in tty without a desktop environment, the result is the same.

I finally found that flog is incompatible with [coc.nvim](https://github.com/neoclide/coc.nvim), it works fine without `Plug 'neoclide/coc.nvim', {'branch': 'release'}`

To be honest, all plugins I used including gitv are compatible with coc.nvim. Maybe it is a bug for flog?

You can reproduce only using vim.rc like below code
```vim
set rtp+=~/.config/nvim/plugged/vim-fugitive
set rtp+=~/.config/nvim/plugged/vim-flog
set rtp+=~/.config/nvim/plugged/coc.nvim
```
Have workaround?

**Comment by rbong** [comment]
I can recreate this, but only on the `release` branch of `coc`. I believe if you switch to the master branch, you will not have this issue.

More context:

The flow when opening preview windows looks like this;
- Try a command
- If the previous command opened new windows, close the old preview windows

Otherwise, the previous window would be closed no matter what, which is not very friendly if a command opens new windows or fails.

Flog does not manually redraw the window so the problem is with coc.nvim

`set lazyreload` does not work, so coc.nvim is redrawing the window. I don't know exactly when, but you search the release branch for `redraw` there are many instances. If you continue to have this issue on the master branch please bring it up to coc.nvim
