### ISSUE TITLE
Launching rebase interactive doesn't work

### ISSUE THREAD

**Issue by jrwrigh** [rbong/vim-flog#23]
The doc says that I can run fugitive commands within the Flog window, but if I press `ri` on a commit to attempt to start an interactive rebase I get the following error:

```
E21: Cannot make changes, 'modifiable' is off
```

Full disclosure, I can't seem to figure out how fugitive rebase is supposed to work to begin with, but it appears that the command isn't even being passed to fugitive at all.

**Comment by rbong** [comment]
`ri` is not a keybinding in Flog, so you get `Cannot make changes` because VIM is trying to replace a character in the Flog window. Any fugitive commands are supported, such as `:Grebase`, `:Gmerge`, `:Gpush`, `:Gpull`, `:Git`, etc. but keybindings are not the same.

The reason for this is twofold: the first is that there are so many commands you can potentially run from a branch viewer that Flog's approach has been to remain extensible and powerful and allow the user to define their own commands or use autocompletion to manually run commands. The second is that a lot of fugitive's keybindings were in flux or not yet added when flog was being written.

To see a list of fugitive commands supported inside the Flog window, see `:help fugitive-commands`. To see a list of keybindings so far in the Flog window, see `:help flog-mappings`, or press `g?` in the Flog window.

If you want to add your own `ri` command, this will roughly do the trick:

```
augroup flog
    autocmd FileType floggraph nno ri :<C-U>exec "Git rebase -i ".flog#get_commit_data(line(".")).short_commit_hash."~"<CR>
augroup END
```

However now that fugitive keybindings seem to have stabilized a bit, I will start adding them to fugitive.

**Comment by jrwrigh** [comment]
Thanks for the explanation! The extensibility makes a lot of sense. Now that I understand that, I could be ok without incorporating fugutive keybindings and just doing custom commands. 

Thanks for the awesome plugin!

**Comment by rbong** [comment]
I just added the following functions from fugitive:

- `dd`
- `dv`
- `)`
- `(`
- `crc`
- `crn`
- `coo`
- `cr<Space>`
- `cm<Space>`
- `co<Space>`
- `cb<Space>`
- `ri`
- `rf`
- `ru`
- `rp`
- `rr`
- `rs`
- `ra`
- `re`
- `rw`
- `rm`
- `rd`
- `r<Space>`

I also had to rework the function system so that all of the commands would work properly, so if you still want to write custom functions it should now be a lot easier and bug-free.
The functions are documented now too, see `:help flog-functions`

**Comment by jrwrigh** [comment]
Sweet! Thanks for the work!
