### ISSUE TITLE
Add ability to reverse diff in visual mode

### ISSUE THREAD

**Issue by fedorenchik** [rbong/vim-flog#28]
diffs in git can be reverted:
```
git diff rev1 rev2
git diff rev2 rev1
```
will show opposite diffs, so to speak.

Please, add support for it in visual mode.

**Comment by rbong** [comment]
I have actually tried out my own custom bindings to do this. I found it way less confusing just to keep the diffs a certain order, since essentially the same information is shown either way. In addition, this would mean that every diff binding will need a reversed equivalent, and I couldn't add new bindings without thinking what the reverse would be, or I would likely get requests to add opposites. It could particularly get rather clunky if fugitive adds a new diff binding, and then all of a sudden we would have to come up with an equivalent. It's just not worth it.

Flog has extensive capabilities for customization exactly so you can add custom bindings like this if you want. Just add this in your .vimrc:

```vim
augroup Flog
  au FileType floggraph vnoremap <buffer> <silent> D :<C-U>call flog#run_tmp_command("vertical belowright Git diff %(h'>) %(h'<)")<CR>
augroup end
```

Where `D` is the binding you want to use for this.

This is using some brand new syntax, so let me explain: the syntax for `run_tmp_command` is similar to `printf` format strings. `%(h'>)` gets the hash at the end of the visual selection, denoted by the `'>` mark, and `%(h'<)` similarly gets the hash at the beginning of the visual selection. Since this gets the hashes in the opposite order of the default diff command, this will reverse the direction of the diff.

**Comment by fedorenchik** [comment]
Thanks, it works!
