### ISSUE TITLE
Use `--` instead of `-` for arguments?

### ISSUE THREAD

**Issue by wookayin** [rbong/vim-flog#68]
I would want to use `--` for arguments (which is more a conventional and standard way), for example:

```
:Flog --all
```

instead of

```
:Flog -all
```

The reason I want this is it is more compatible with raw `git log` command so I can have the same code for generating raw `git` command lines and `:Flog` commands.

So it'd be nice to have all arguments coming with double dashes. For backward compatibility we could keep the single-dash arguments. Any thoughts?

**Comment by rbong** [comment]
Flog uses a more similar argument format to builtin vim commands. Flog arguments are not shell arguments, they are arguments for a vim command. It translates any arguments that go to `git log`. Flog also doesn't aim for feature parity with `git log` arguments, some of the things a shell command does are difficult to do in vim.

That said if this issue gets support I would be willing to switch. This is just the ideas that went into how it works now.

Backwards compatibility may not be something I want to do, I don't want to maintain both forever. If it ends up being easy, though, I would support both until it becomes unfavorable.

**Comment by ferdinandyb** [comment]
I sort of like fugitive's way of `:Git [whatever]` is almost always the same or very similar to `git [whatever]` on the CLI. On the other hand with `:Flog -- [whatever]` you can pretty much get the same thing I guess? But I do have to not, I run into it often enough that I want to do a `git log [something]` in Flog and type double dash options.

**Comment by rbong** [comment]
> I sort of like fugitive's way of `:Git [whatever]` is almost always the same or very similar to `git [whatever]` on the CLI. On the other hand with `:Flog -- [whatever]` you can pretty much get the same thing I guess? But I do have to not, I run into it often enough that I want to do a `git log [something]` in Flog and type double dash options.

Thank you very much for weighing in. We need all the feedback we can get on this issue.

I should explain that for the most part, Fugitive commands correspond directly to a git command because that's just... well, what they are. Flog on the other hand is much less a direct analog for `git log` than any Fugitive command is for its corresponding Git command.

When you are passing arguments to `Flog`, you are passing arguments to a Vim command. It may translate those options to a Git command, and I might try to keep argument name parity, but it almost always is doing something extra inbetween inside Vim and it may not work exactly the same - in some cases they're implemented entirely internally.

The biggest thing is that as long as Vim cannot complete arguments in the form `-arg "quoted arg with spaces"`, we can probably never have complete argument parity. So be aware that when you're asking for this, you're not asking for arguments to be the exact same as `git log`, you are asking them to be a bit closer but still required to be specified in a different way.

There definitely will be issues where people are confused why they can't specify arguments with quotes if we do this, so please weigh that against stylistic preference for double dashes.

**Comment by ferdinandyb** [comment]
On Fri Jul 19, 2024 at 20:00, rbong ***@***.***> wrote:
> > I sort of like fugitive's way of `:Git [whatever]` is almost always the same or very similar to `git [whatever]` on the CLI. On the other hand with `:Flog -- [whatever]` you can pretty much get the same thing I guess? But I do have to not, I run into it often enough that I want to do a `git log [something]` in Flog and type double dash options.
>
> Thank you very much for weighing in. We need all the feedback we can get on this issue.
>
> I should explain that for the most part, Fugitive commands correspond directly to a git command because that's just... well, what they are. Flog on the other hand is much less a direct analog for `git log` than any Fugitive command is for its corresponding Git command.
>
> When you are passing arguments to `Flog`, you are passing arguments to a Vim command. It may translate those options to a Git command, and I might try to keep argument name parity, but it almost always is doing something extra inbetween inside Vim and it may not work exactly the same - in some cases they're implemented entirely internally.

I already realized, that `:Flog -format` is already doing `--pretty=format:` in the background so there's already some discrepancy.

>
> The biggest thing is that as long as Vim cannot complete arguments in the form `-arg "quoted arg with spaces"`, we can probably never have complete argument parity. So be aware that when you're asking for this, you're not asking for arguments to be the exact same as `git log`, you are asking them to be a bit closer but still required to be specified in a different way.
>

And I did run in to this whitespace quoting issue as well. So I'd say it might make sense to just leave it as it is. It's not particularly hard to remember to use `--` for verbatim passing of parameters. And since escapes sequences like color don't pass to vim, using raw output isn't really an option in quite a few situations anyway.

> There definitely will be issues where people are confused why they can't specify arguments with quotes if we do this, so please weigh that against stylistic preference for double dashes.

Agreed.




-- 
+36305425054
bence.ferdinandy.com

**Comment by rbong** [comment]
[v3 is coming out](https://github.com/rbong/vim-flog/issues/135), so if we're ever going to change it the moment is now. If there is large support for this change I will change it, otherwise I'm going to stick with what we have and close it after v3 is out, unless if Vim or Neovim changes.

To reiterate one more time why it's like this now, arguments to `:Flog` are for a vim command, not for a shell command. Arguments follow the style of commands like `:command`, which use a single dash. Arguments in the style of a shell argument will *not* work, and we can't add full support for them until Vim/Neovim can complete arguments like that. But I will still listen to the community if this is the preference.

**Comment by wookayin** [comment]
> not for a shell command. Arguments follow the style of commands like :command, which use a single dash

Well, if you think arguments to vim command is different from the standard convention in the shell CLI commands, we may want to use `arg=value` styles. Just single dash only `-` is, in my opinion and only adds confusion.

**Comment by rbong** [comment]
Thank you for your feedback.

Looks like we are sticking with a single dash for now though because not many people seem to feel strongly about it, or at least it's hard for me to tell if they do. I'm going to close it because it's been open so long and everything has been said. Feel free to give this a thumbs down if you want Flog to support both.
