### ISSUE TITLE
Difference from Gitv?

### ISSUE THREAD

**Issue by Mike-Now** [rbong/vim-flog#7]
What are the selling points of this plugin as opposed to [Gitv?](https://github.com/gregsexton/gitv)

**Comment by rbong** [comment]
- Higher stability. Flog is built from the ground up with lessons learned from Gitv. Feature requests are much easier to accommodate and it's been much quicker and easier to fix bugs.
- Hackability. Flog exposes its API in order to allow for adding your own features. Most notably, you can open any command you want in a preview window and retrieve any information about the commit graph. The API and internal state are organized and readable.
- Customizability. Flog supports custom, multiline log formats. Any window layout is supported. The bindings are more simple and vim-like to customize.
- Power and efficiency. Flog allows you to run any git command on the commits under the cursor using the :Floggit command instead of including tons of different bindings for every git command under the sun with every different flags.

Let me know if you have any questions!
