### ISSUE TITLE
Feature request - Populate Quickfix/Location List 

### ISSUE THREAD

**Issue by dsirov** [rbong/vim-flog#71]
If Flog would enable (optionally) populating quickfix or location lists (hopefully supporting both) this may further simplify prev./next commit browsing without jumping back from the commit buffer (window) back to Flog.

[Fugitive does this and it is quite handy...]

**Comment by rbong** [comment]
Thanks for the feature request!

This is my first time hearing about this feature. Can you elaborate a little bit more about how Fugitive populates the quickfix/location list and how you might use it so I can understand the feature? What does Fugitive populate into the lists? How might you use this?

**Comment by rbong** [comment]
It didn't quite click when reading the documentation for Fugitive but I've had a chance to actually try `:Gclog`/`:Gllog` now and I think I understand what you're looking for now. You want to be able to populate a quickfix list with the commits that show up in `:Flog`, instead of writing them to a buffer and showing them in a normal window, is that right?

There may be a lot of difficulties showing commits in a list rather than in a buffer here but let me also make sure I understand your core problem:

>this may further simplify prev./next commit browsing without jumping back from the commit buffer (window) back to Flog

Is this the issue that you're describing?
* Open a commit in Flog
* Go into the temporary window with the commit
* Want to go to the previous/next commit, but have to go back to the main Flog window to do so

If not, could you describe this issue?

Are there any other issues lists would solve?

**Comment by dsirov** [comment]
I think this is mainly relevant for browsing, which is made especially easy with the [unimpaired](https://github.com/tpope/vim-unimpaired) plugin, which introduces ]l and [l for location list and ]q and [q for quickfix list prev./next shortcuts.

You may want to check out this great [video blog post](http://vimcasts.org/episodes/fugitive-vim-exploring-the-history-of-a-git-repository) which deals specifically with history browsing using fugitive and quickfix list.

**Comment by rbong** [comment]
It's been a while, I can re-open if you'd like to provide more details about how this should work.
