### ISSUE TITLE
`vim-flog` vs junegunn's `gv.vim`?

### ISSUE THREAD

**Issue by subnut** [rbong/vim-flog#74]
I am currently using [junegunn/gv.vim](https://github.com/junegunn/gv.vim)

Should I switch to this plugin? _Why_ or _Why not_?

**Comment by rbong** [comment]
[Flog v2](https://github.com/rbong/vim-flog/issues/73) is in development which has more differences from v1, I'll be touching a bit on that.

gv.vim is an ultra-light branch viewer, where Flog is a fully-featured branch viewer.

All gv.vim does is run `git log --graph` with a predefined format and allows you to open commits. If that's all you need, you should use gv.vim.

In comparison, Flog, and especially Flog v2, can be used as a complete branch viewer, more akin to something like gitk. I'll go over some of the things you can do later, but essentially it lets you customize everything, navigate anywhere, and do anything.

Flog v2 goes so far as to draw branches itself rather than relying on `git log --graph`. In this sense it could be called the first "true" branch viewer for vim, not a hack. We can do a lot with this, and probably will be doing more in the future.

Concerning speed - v1 was significantly slower than GV, but v2 is only slightly slower (<100ms per 10,000 commits in the Linux repo). You can see a comparison [here](https://github.com/rbong/vim-flog/issues/73#issuecomment-1021747577). For this small performance hit you get a fully featured branch viewer. Flog v2 is so fast because it is a total rewrite in vim9script and Lua - so if you don't want to install Lua and don't want to use Neovim (not yet supported) you should avoid Flog.

Here's some features of Flog that aren't part of gv.vim:
* Customize the output using `--pretty=` syntax from `git log`, multiline formats are supported
* Settings to specify default options
* Run `git log` commands which contain inline diffs, complete with syntax highlighting - ex. visually select lines and type `:Flog` to get history just for those lines with inline diffs
* Update output without re-running the command
* Use familiar keybindings from Fugitive
* Bindings to toggle and change arguments  to `git log`
* More ways to navigate the graph using keybindings, including jumping between commits with refs (ex. branches) with `]r`/`[r`
* Many more useful Flog-only bindings, ex. `cob` to checkout the branch under the cursor
* Functions to easily define your own keybindings and commands that can perform operations based on the commit under the cursor and other contextual information
* Robust window management system for custom commands - ex. open windows containing commits anywhere, not just vertically to the right. You can also open multiple windows at once
* `:Flog` itself can open anywhere, ex. in a split
* Contextual git command completion - complete the hash, remote, branch or tag under the cursor and more
* Intuitive "commit mark" system mirroring vim's "marks" that allows easily doing commands on 2 or more commits, and more - ex. can perform a diff between two different commits

v2 only features:
* Beautiful and easy to read graph output using unicode characters
* Accurate branch highlighting

Let me know if you have any questions.

**Comment by subnut** [comment]
Thank you for the detailed explanation!  

(SUGGESTION: Maybe pin this issue to help others having the same question? :shrug:)

**Comment by rbong** [comment]
Be aware that Flog's speed is now comparable to GV, up to tens of thousands of commits.
