### ISSUE TITLE
[Feature Request] log viewer support changes entry

### ISSUE THREAD

**Issue by fcying** [rbong/vim-flog#75]
in log viewer, also have changes entry(Untracked changes and Staged changes)

e.g. (from tig)
![image](https://user-images.githubusercontent.com/106934/155690266-269b763e-015a-415a-915f-3c9431720496.png)
![image](https://user-images.githubusercontent.com/106934/155690088-02c9c603-49ea-49dc-849d-9d44e27ee2bd.png)
![image](https://user-images.githubusercontent.com/106934/155690128-d3813697-e431-40b2-af97-9e3f7aa71c3f.png)

**Comment by rbong** [comment]
### Summary

This might seem like a no-brainer feature to add, but actually there are a few issues to consider here.

The issues are:
* Formatting: it is currently impossible to display staged/untracked changes in a nice way, and it may never be possible.
* Usability: while it may be nice to have staged/untracked changes in a typical log viewer, there may be better ways to accomplish the same thing in Flog.
* Commands: adding staged/untracked changes will not work with how Flog runs commands internally, and it will make user customization using the command system harder.

The first two issues can be lived with, but the last issue is currently insurmountable for issues I describe below.

For now, I am adding the `gs`/`gu` to show staged/untracked changes in [v2](https://github.com/rbong/vim-flog/issues/73).

### Formatting issues

Even v2 relies on `git log --format=...` for controlling how the commit looks, so we can't just create a nicely formatted line for staged/untracked changes. Here's what it might look like.

![2022-02-26-114111_1467x244_scrot](https://user-images.githubusercontent.com/5875706/155853777-4a538f2b-0c34-4f89-a873-81ef5e617e36.png)

So just be aware that if we add this feature, it's not going to look great until we start handling formatting ourselves, which is not currently a priority. That's going to require to switch to libgit and replace a bunch of git internals, and I'm still not sure if it's worth it.

Let's consider this feature without worrying how it's going to look for now though.

### Usability issues

As far as I can tell there are a couple reasons people like to see staged/untracked changes in log viewers:
* To tell at a glance whether staged/untracked changes are present
* To be able to quickly view staged/untracked changes

(If there's another reason you would like this feature, please let me know.)

Log viewers handle these two things by displaying the staged/untracked items with other commits because that's all they can do. They are log viewers and nothing else. However, Flog lives in Vim and relies on Fugitive - is this the best way to handle these two features within that context? Let's consider this question.

#### What is the best way to handle: "tell at a glance whether staged/untracked changes are present"?

In most log viewers, there are two places you can display staged/untracked changes:
1) Above the current `HEAD`, which is technically more accurate but means you can't see/access staged/untracked changes if the current `HEAD` is not in the graph, and it can make it harder to find the staged/untracked changes if the `HEAD` is not at the top, which contradicts the desired functionality.
2) At the very top at all times, which is more convenient, but does not really have a place along with everything else shown in the log viewer. This is more convenient - but still not super convenient. Whenever you want to view staged/untracked changes, you have to jump to the very top.

In the context of Flog, in my opinion, there are two better ways to show whether staged/untracked changes are present:
* In the statusline. This has the advantage that you could create a statusline that displays whether there are staged/untracked changes at any time, not just when you're in Flog - why, after all, would you only want to know this at a glance while using Flog?
* By running the `:G`/`:Git` command without any arguments. This is the solution I use.

#### What is the best way to handle: "quickly view staged/untracked changes"?

As I've already established, the typical way that log viewers handle staged/untracked changes can make it inconvenient to jump to them in the branch graph. By extension, it also makes it inconvenient to view staged/untracked changes.

The best way to handle this in my opinion is to add bindings to view staged/unstaged changes. I don't like to just add random bindings that have no equivalent Fugitive bindings to avoid conflicts, so I didn't add these before, but since creating Flog, Fugitive has added `gs` and `gu` to jump to staged/untracked changes. I will borrow these bindings to show staged/untracked changes in Flog.

This change will have to be in v2, since `gs` is currently used in v1 and I don't want to break that.

### Command issues

There's another issue with showing the staged/untracked changes in the graph, these items would be incompatible with how running commands in the commit graph.

Let's take the example of the `dd` binding (v2).

```vim
nnoremap <buffer> <silent> <Plug>(FlogVDiffSplitRight) :<C-U>call flog#ExecTmp('vertical belowright Git diff HEAD %h', 0, 0)<CR>
```

Of note here is "Git diff HEAD %h" - this means diff the current HEAD with the hash under the cursor. Staged/untracked changes do not have hashes - they are uncommitted changes. It will need a different command entirely.

Most bindings in Flog work the same way - they expect a hash under the cursor. For each one, we need to consider if we can still use the binding, and then implement not one but two special cases for the binding.

It's not really an issue to do this with our internal bindings, but there's another problem - this is not just an internally used system, it's intended as a user-facing system that they can use to easily implement their own bindings. This will make it harder for users to add bindings, and even if they don't care about these special cases, it will make it significantly harder to copy and modify the original bindings to customize them.

The ability to easily create new bindings and copy/modify bindings is a big reason why Flog exists in the first place. To implement this feature, I would need a very good reason, or a way around these issues.

**Comment by rbong** [comment]
I've added the following to v2 to mirror Fugitive:
* `gs`: show currently staged changes.
* `gu`: show currently untracked/unstaged changes.
* `gU`: show currently unstaged changes.

**Comment by fcying** [comment]
add an identifier to the title bar? That way I can know whether to open changes view.
![image](https://user-images.githubusercontent.com/106934/155917835-6f1da561-874c-4e3f-95c8-42f893616e9f.png)

by the way, Will this feature be added to V1?

**Comment by TamaMcGlinn** [comment]
@fcying install [vim-airline](https://github.com/vim-airline/vim-airline/#flog) to see if there are changes

**Comment by rbong** [comment]
>add an identifier to the title bar?

I wouldn't want to put an identifier in the title bar unless if there's a lot of support for this idea - in my opinion, it's already very crowded.

>Will this feature be added to V1?

I cannot add the bindings to v1 because it bindings starting with `gs` already which means there will be a delay every time `gs` is used. This type of conflict makes it hard to add a deprecation warning, so I am saving it for v2.

However I have just added the `%t` format item, which the unstaged binding relies on, to v1, so if you would like this feature you can add it yourself.

```vim
au FileType floggraph nnoremap <buffer> <silent> gs :<C-U> call flog#run_tmp_command("vertical belowright Git diff --cached", 0, 0)<CR>
au FileType floggraph nnoremap <buffer> <silent> gu :<C-U> call flog#run_tmp_command("silent Git add -N . \| vertical belowright Git diff \| silent Git read-tree %t", 0, 0)<CR>
au FileType floggraph nnoremap <buffer> <silent> gU :<C-U> call flog#run_tmp_command("vertical belowright Git diff", 0, 0)<CR>
```

**Comment by fcying** [comment]
Thanks, this is exactly what I need.

**Comment by friedow** [comment]
Hey :), sorry to revive this issue, but is there any way we can get this nicely visualized just as you posted above @rbong with vim-flog v3?

I really like the flow of jumping through the graph and selecting commits to checkout. However, I commonly find myself not seeing that I still have unstaged / staged changes. My neovim config is pretty minimal in terms of UI and I don't have any bars to visualize that there are unstaged changes. Thats why it would be very nice to have this shown inside the graph directly.

> ![image](https://github.com/user-attachments/assets/c6ad977d-8f8f-4dc0-9b75-8cff20c6b2bf)
