### ISSUE TITLE
Multifile side by side diff

### ISSUE THREAD

**Issue by mflova** [rbong/vim-flog#76]
I have been reading about the possibilities of this plugin and I like its potential (specially this Flog V2) congrats! 
Among the features I feel it is missing, is the multi-file diff. By default, these diffs are inline diffs in a single buffer. Meaning a few drawbacks: no proper color syntax and high diffs become harder to evaluate or navigate.

I have been searching for ways to improve this and I found that there are a few plugins that are already working with this:

- Octovim offers a PR review system in which you can navigate between different changed files and the diff is displayed side by side
- Diffview displays side by side views between any arbitrary commit, revision or branch. This one is not integrated in any commit browser

My questions are: is there a way this plugin can integrate a system like this? I understand that this might be out of the scope, and the problem is that plugins like Diffview are neovim-based. I would also like to know if there is a way for me to create a new command in my config and that I can map like

```
:DiffviewOpen commit1 commit2
:DiffviewOpen branch1 branch2
```

Being `commitX` or `branchX` the result of the visual selection in vim-flog

Thanks!

**Comment by rbong** [comment]
Flog is not limited to working with the `Git` and `Floggit` commands, for example look at the `Flogsplitcommit` command:

```
command! -buffer Flogsplitcommit call flog#Exec(flog#Format('<mods> Gsplit %h'), 0, 1, 1)
```

The arguments to `flog#Exec` are:

* `command`: The command to execute
* `focus`: Whether the window that is focused at the end of the command should retain focus
* `static`: Whether the commit graph should be updated after running the command
* `tmp`: Whether the windows opened by the command are temporary (whether they'll be closed when running a new command)

When you call `:Floggit`, it's really just calling `flog#Exec` with `:Git` under the hood.

`flog#Format` may be familiar to you from other examples, but in case it's not, it pulls some data from Flog and replaces parts of the string with it. It can do a lot, check out `:help flog-command-format`.

The way you've described it, you want to create a command that opens a diff for `commit1` and `commit2` if you enter `DiffviewOpen`. The way you would do this is:

```
au FileType floggraph command! -buffer -range -nargs=2 FlogDiffviewOpen call flog#Exec('DiffviewOpen <args>', 0, 1, 1)
```

This could call the `DiffviewOpen` command from DiffView, complete with Flog completion and a temporary window.

However you may wish to create a binding instead and use `flog#Format`, here are some ideas (they all use the `d*` binding):

```
# Compare the commit under the cursor with the current HEAD
au FileType floggraph nno <buffer> <silent> d* :<C-U>exec flog#Exec(flog#Format("DiffviewOpen %h"), 0, 1, 1)<CR>

# Compare the last interacted commit (ex. the last commit you hit "Enter" on) with the current HEAD
au FileType floggraph nno <buffer> <silent> d* :<C-U>exec flog#Exec(flog#Format("DiffviewOpen %(h'!)"), 0, 1, 1)<CR>

# Compare the commits at the beginning and end of the visual selection 
au FileType floggraph vno <buffer> <silent> d* :<C-U>exec flog#Exec(flog#Format("DiffviewOpen %(h'<) %(h'>)"), 0, 1, 1)<CR>

# Compare the commits at mark "a" and "b" (commits can be marked with "ma"/"mb")
au FileType floggraph nno <buffer> <silent> d* :<C-U>exec flog#Exec(flog#Format("DiffviewOpen %(h'a) %(h'b)"), 0, 1, 1)<CR>
```

I'm closing since I took so long to reply and don't anticipate a response (sorry about that) but please let me know if you have any more questions.
