### ISSUE TITLE
`graph.lua:404: table overflow` in v2 branch.

### ISSUE THREAD

**Issue by kevinhwang91** [rbong/vim-flog#89]
`git rev-list --all --count` outputs only `603`.

I have use `nvim --clean` to reproduce it, no idea why this issue happens.

Edit: I bisect commits and found the culprit is that the commit without files changed.

**Comment by rbong** [comment]
Please let me know if you have a repo I can recreate this in. I did have a repo I was having memory issues with, but it stopped happening. I did try creating some empty commits, but was not able to recreate. It's likely more factors involved than just empty commits.

**Comment by rbong** [comment]
Actually I was able to reproduce some kind of memory issue, it happens when one commit has two identical parents. I am not sure if this is exactly what causes your issue but it's fixed now.

(Side note: I'm not going to display on the graph when one commit has another commit as a parent more than once. It's too much of an edge case, it messes with optimization, and it's not extremely useful information to show AFAIK.)

Please let me know if it's fixed for you. Otherwise, I could use a repo to reproduce this, or at least the output of this command:

```
git log --parents --topo-order --no-color --pretty=format:"%h %p" --max-count=<count> <rev>
```

Where `<count>` and `<rev>` are the values you need to create the issue in Flog.

**Comment by kevinhwang91** [comment]
Thanks, fixed now. Yes, you are right, a commit with two identical parents added by  `JetBrains/IdeaIC202x/settingsRepository/repository`
